plugins {
    id 'com.android.application'
}

android {
    namespace 'de.meinetodos.app'
    compileSdk 34

    defaultConfig {
        applicationId "de.meinetodos.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "meinetodos"
            keyAlias "meinetodos"
            keyPassword "meinetodos"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
